version: '3'

services:
  mysql-debug:
    image: docker.io/leo18945/mysql-debug:5.7.29
    container_name: mysql-debug
    user: root
    ports:
      - '13306:3306'
    # volumes:
      # - ./my.cnf:/etc/my.cnf
      # - ./docker-entrypoint.sh:/work/docker-entrypoint.sh
    # environment:
      # - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024m
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

# docker-compose run -u root --name mysql-debug --service-ports mysql-debug
